spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info