### 
curl https://api.stripe.com/v1/payment_methods \
  -u "sk_test_51SHzeXErBBJq2QWl9vIjCQLVthYtLNYQNoTiMerYB00JtVqJNlhMI8zIF1BxD2SqRoHXwtSVAfeT65Y183POjivN00ASPpGmEz:" \
  -d type=us_bank_account \
  -d "us_bank_account[account_holder_type]"=individual \
  -d "us_bank_account[account_number]"=000123456789 \
  -d "us_bank_account[routing_number]"=110000000 \
  -d "billing_details[name]"="John Doe"


###
GET http://127.0.0.1:8081/consumer/sayHello?name=world


### dubbo-grpc
###
GET http://127.0.0.1:8082/consumer-grpc/sayHello?name=world2


### nacos demo
GET http://127.0.0.1:8080/nacos-demo/hello2

###
curl -X GET "http://localhost:8848/nacos/v1/cs/configs?dataId=nacos-demo.properties&group=DEFAULT_GROUP"

###
GET http://127.0.0.1:8089/etcd/test


###
GET http://127.0.0.1:8080/zookeeper-demo/name
###
POST http://127.0.0.1:8080/zookeeper-demo/name?value=jet1

{}
###
DELETE http://127.0.0.1:8080/zookeeper-demo/name


###
POST http://127.0.0.1:8080/redis-demo
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "n1"
}

###
GET http://127.0.0.1:8080/redis-demo/74fe5cfb-802b-4e72-89d0-5e90a005207c

###
DELETE http://127.0.0.1:8080/redis-demo/b0b0df09-b180-4d81-8f45-ea5f0a7970e1



### 
POST http://127.0.0.1:8080/kafka-demo/send
Content-Type: application/json

{
  "topic": "demo-topic",
  "value": "hello: {{$guid}}"
}



###
POST http://127.0.0.1:8080/elasticsearch-demo
Content-Type: application/json

{
    "name": "Alice",
    "age": 24,
    "bio": "Love distributed systems"
}

###
GET http://127.0.0.1:8080/elasticsearch-demo/Alice


###
POST http://127.0.0.1:8080/mongo-demo
Content-Type: application/json

{
    "name": "Bob",
    "age": 24,
    "bio": "Love distributed systems"
}

###
GET http://127.0.0.1:8080/mongo-demo

###
GET http://127.0.0.1:8080/mongo-demo/search?name=Bob



###
GET http://127.0.0.1:9001/langchain/memory/write?id=1&question=黑
###
POST http://127.0.0.1:9001/langchain/embedding/hello?question=你好

###
GET http://127.0.0.1:9001/langchain/embedding/query?question=你好

###
POST http://127.0.0.1:9001/langchain/rag/add?path=D:\Cache\ESJZone-novel-mirror-main\Novel\日輕\半龙少女.txt
###
GET http://127.0.0.1:9001/langchain/rag/chat?id=1&question=介绍一下半龙少女的艾露

###
POST http://127.0.0.1:9001/langchain/mcp/chat?question=请使用howtocook的MCP服务为4人晚餐推荐菜单


###
POST http://localhost:11434/api/generate

{
    "stream": false,
    "model": "mannix/llama3.1-8b-abliterated:q4_0",
    "prompt": "xie"
}


###
GET http://127.0.0.1:9001/springai/hello3?prompt=你是谁