spring:
  datasource:
    url: jdbc:h2:mem:jobrunr-demo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8000
logging:
  level:
    org.jobrunr: DEBUG
