server:
  port: 8080

xxl:
  job:
    admin:
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://localhost:8089/xxl-job-admin}
    executor:
      appname: xxl-job-demo-executor
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token

spring:
  application:
    name: xxl-job-demo
  datasource:
    url: jdbc:h2:mem:xxljob;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ''