dubbo:
  application:
    name: zookeeper-dubbo-grpc-provider
    qos-port: 22222
    logger: slf4j
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: tri
    serialization: protobuf
    port: 50054