dubbo:
  application:
    name: zookeeper-dubbo-grpc-consumer
    qos-port: 22226
    logger: slf4j
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: tri
    port: 50056

server:
  port: 8082