name: xxl-job-demo Docker CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Give Gradle wrapper execute permissions
        run: 


      - name: Build with Gradle
        run: |
          cd task-demo
          chmod +x ./gradlew
          ./gradlew :xxl-job-demo:clean :xxl-job-demo:build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f xxl-job-demo/Dockerfile -t cuijj/tasxxl-job-demo:1.0.0 .

      - name: Push Docker image
        run: |
          docker push cuijj/tasxxl-job-demo:1.0.0
